sudo: required
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'
matrix:
  allow_failures:
    - node_js: '5'
  fast_finish: true
before_install:
  - git clone git://github.com/ladislav-zezula/StormLib.git
  - cd StormLib
  - cmake CMakeLists.txt
  - sudo make install
  - sudo ldconfig
  - cd $TRAVIS_BUILD_DIR

  - git clone git://github.com/Kanma/BLPConverter.git
  - cd BLPConverter
  - cmake CMakeLists.txt -DWITH_LIBRARY=YES
  - sudo make install
  - sudo ldconfig
  - cd $TRAVIS_BUILD_DIR
script: npm test --coverage
after_script: codeclimate < coverage/lcov.info
