language: node_js
node_js:
  - '0.10'
  #- '0.11'
before_install:
  - git clone git://github.com/ladislav-zezula/StormLib.git
  - cd StormLib
  - cmake CMakeLists.txt
  - sudo make install
  - sudo ldconfig
  - cd $TRAVIS_BUILD_DIR

  - git clone git://github.com/Kanma/BLPConverter.git
  - cd BLPConverter
  - cmake CMakeLists.txt
  - sudo make install
  - sudo ldconfig
  - cd $TRAVIS_BUILD_DIR
